language: java
jdk: oraclejdk9
branches:
  only:
  - master
before_install:
- sudo apt-get install -y rpm2cpio wget
- nvm install 10
install:
- epmd -daemon
script: make travis
before_script: make travis-init
before_deploy: make travis-deploy
deploy:
  provider: releases
  api_key:
    secure: Q+kKbLBmZkrraaJ5zEurVaRIcfGSZPP1jocyaB32Cu645M9ZYJcO0gueNDfkqpU3Em4vVcxreiRFrBZ07lKGicinvJApfxu7dAjMRrAXGaajhJ3Fs8OUR6rUfdEfSo3bI5szmncLkNt9LYQbjGCY9wgux0oARAYHjfUZrRfKuBe3Zb26iEwWEfE6UCUWSgS79Wjzv8QvQxtLXmGsYgXW3WEozrjJvjlv+8rEBLwfFR0F/xasiv0/gZQOJMubqmL8Bm4/bEpjIRLZf4LgjXm+kWlmCCmojb0cTbi8rVyVvQ36guG5Nyj2txOsqzX6w3+oiwAm3XvB5PxAFrYWPrVQBLKSyJ3J/IlLojyLzYSSCG1+27VpMSi8g8ySt89vGaT1DNH9Td1CwB55Mb5Cw1ZYjHu2EF96zJr5/RCXABCwfVqykCHk4rrHe6DYR08sQsNDhYbDmiMTmuzuASNIvBG+IITiWlZSsk2ixBooNenjT1EEup3c65ITA+0ElZ5pylJe+wzmwyaTxI0rvKCZY2DrPZGtNqn7PNYQP91oFOAXtltIOZkUhPeFLl9NLoNNOu5bLj+LBPKEq/VhZcwxYrhXemkSpuMNGNY/3LlY627gFqehaQ47uQXbH0DQqQ4PEpWccaCP6Mf44R7lIFXTsCNm9jjkJ8Z1vIv9Hey2rB6hOZg=
  file_glob: true
  file: 
    - core/build/libs/*
    - did/build/libs/*
  skip_cleanup: true
  on:
    repo: ArcBlock/forge-java-sdk
    branch: delegate
env:
  global:
  - secure: O0rJCpkwbo0LcbPVbuGyS3JOVKUTvvOe/hf5tYpCjmF6kaSHTwKCmkMAIZAqNCu+RG2ur3BmfeBv2E8tsUP0YwfWopPpvGHRSoHeNfJpFefCFDi38Q931Go4an5mqSBCfxGDHT4k7OGQKQ3jLy1HKIFFViWXutheFJWaaqgZFsf7sVz+l02ZJ9bKdKxOKswS0yOmyiGrRVi/j1lDSyGWfaCYt9nG9ESJVqgtkTQ9tqzUrh78+fa4CwbJnToos2ZdyBAHoNkWyLIfmXRc9cCrVBcTs5mAaYuZ5k0jky5yQrNbUwBHEqM9OMn/M/LRsUGtkPmcNFWPbLzuY5c8BE6xIzGtKHpNR5ROgBoyQHavdMet/2zMLxchqEqKNHOO6pdno0RteSgyrxC/EcbHYxosIR0q+Aay9jKsqbQ8X9vlBEecVDx1+2qqrOm3FurKK3jKX3VwuzYAAwV54tfTUYW7K7c1k61Bs7M/LS1madby+Ic8zY5x4unGbH3s2KUbskEMyrlfnssrI82bdTUjp2weSSqF1p5m652prNQq64WA6jtoOpZP14gO/6pS1VHw/DbiqI3DUP19iyKjy06RMarT8RS27n4hUSES4KuZDlVPFJyROHQ2Y89LpWZETtFDoLKZ8vQRE7F4WtAFTVY4GANeZlMVKwt0tYkMJFioZnaxeSo=
  - secure: nj2huH1ENrt53+wRW2dnIVzBBVvl+dViKFn/e1GcmG1a200xcTRoqm+M9VIa2xePWXWOYQK1K1EJxXDuZ33oqcLNnnC7V605ItLADDhlheb7pJtTh6wSImZbE4cYxTVPNSWm1cNecwZW77ylVb06CLvCXtiNfm/1WobQqA8Q3173EzSixRimXgj7uDtAJqg8ObCmLYvmMyY0+O/FNZkqgU5nkt3ebf6dNg6ExUNCRl4aYoZ3SKkNQtEWV1F9K/nk4NCS7+Kuuf4RFY+1Di+Mv5YQJtOwEfHPWLrGCmaZLrxNqbGPjokdqL9kk4Ms6l79S8QA/Uwkf+HT2uNHbs9voyx1jLmuJTtuwW4RweKxl8oFbbsQ2loHOnEXDdl+CdnWproWkDtxUbxGxGVHocxASn/MDmlx1Yut/hMZbaTjFQ1ZzxYW66QLZRBj/8VlBfPiyvTwi1pOssemUD5uVFEuOjICTl0I+Jc6mxBVydzPeLVm1G5Y3olAot5vgsKVKC5PURND2xkRPFu9sTr4SueoMxszSymm6tOYmbClMqXt40/dGU6+QwCl5trWN/qXae5sSqbdtAb7UAROp2Or8cDstk2Z1fLfO4REwbsylVa0HYeKfxA9CtTCgWpFBJETOcGt/p4uWbTw2A+8ScOuAU5CLbK0PlmJR5EHh4WNkB0FeBI=
