language: java
jdk: oraclejdk8
branches:
  only:
    - master
before_install:
  - sudo apt-get install -y rpm2cpio wget
  - nvm install 10
install:
  - epmd -daemon
script: make travis
before_script: make travis-init
before_deploy: make travis-deploy
deploy:
  - provider: releases
    api_key:
      secure: lNOYIF0IXGIToG4qzPtWKRdEzj85S0+KxahWSZimJ2FitpbYjCMLk9H20zghKd6JlGteSG51i974wxGDzBkcAWVP1/CidmwJBgd6tKufk+/HKPTknMCVUv9pCYYx4VZDbKJq5/TLs8SXbnMTgYw1tzBZm2BAHrkkswy0QO8qDGNyqZJO7CDbs1LxqWrvV4RnjBknftJEiyg21I0TBmKRppZEC/BiNUAnJSLeJCz+ruUD+wtgzeBIYHLhucL8zqfxoXWvXEY8jhNPFs17B+p1P+GiAhYSBvUccine3hvP9cwXUumxOaTr0qPU9Dansuaa0xNeruRd2r3srB369Z03YMijiTxKDIrg7KRZj/SFQxFBWr7sHRvcDmHk1dQ4ovSa1+fdJ9pbukvxpCZNMlXo2vDjmf4L1gnO8H53NW3A7zKHDNuTmPoEvgAxo8sP2TcBSVl9BQfMVh30JHKU+5PkwaJgmwEAq59CJbbPc0dfTw63q/vXwG2Nx3t2oJwRK2l2bv6KSoyyNnNjiIrsg5rHh0plm0pG5RgQRxBT4E4fk9X2/S3c1Zp4waQAgIH9vlhmOhq7x/4RGASd9hOPvSAFhe9ek2zPgD4YuwWdnI5Tq70Mk/5qbCYddK0DR+wteVWpE6fqqDwW/OBoMun/RA2ySIjkPV+0uqUa6XeECSeSYq8=
    file: build/libs/*.jar
    skip_cleanup: true
    on:
      repo: ArcBlock/forge-java-sdk
      branch: master
  - provider: s3
    access_key_id: AKIAJMQME6TJ4NT6BJ7A
    secret_access_key:
      secure: KSH3iXfRizsNLuWdFjo+vRiY7qKJAAkOheX/N5Mcp1oUBoSXQURYmFM6+xQJwOpUntWn3jWdqICSOA7/iVgsfk6f4WPo1Z6Nwlb/8JpPpVlrjz3F12J4+1s1NDX8zVWSxgqVaiIXCJ+Gq7wYvhbd0Wr12GXQLbACc25q1biZlA/HBCeA5t9cH/rVqzRdPJ6n1U6wjsAqSGV9pb1xdORy0s95z8gvNvhVzydaXVUOS9HICWk8f8CzFOYmaFmEFVXoV05KAE9v2YzBw06pjSNdIIHWDUZohndYfHf1k73S+f2viw6N6SMmz2B5BgWTPGUzKbj/Sa7SvyMCjCHsiashjDRzOdXlZSvK09XM1VLmSq39AFc0fyOJAZNV7W5FBI6+kzK0NyTzOHxHVY2oGWeWsREwapI13KW0v68IbIEsAIU0LDhxPcFs+TKkF4RPVBqQog7/rSZDrDhgxDNo3ES1ijQf51E5Q4y4nh+rojyIZ+r5y+W0IemPW5LkzvaX51pau7U5+7bgD1svoB6meXoBVpQ9yU/f/QhrRYolcqdGBfzLHuo/DzMnM83ZrMY1ZSroRhyRIOpcuQnNDyMuW4pECV1jXLFHH99CcHtZnVpZ+hydmR06WuYvY20RNBbn5+5sDx/17jK65/9feCUX0irMzdENleILfmohv3ykJ1uig4g=
    bucket: android-docs.arcblock.io
    local-dir: docs
    skip_cleanup: true
    region: us-west-2
    on:
      repo: ArcBlock/forge-java-sdk
      branch: master
env:
  global:
    - secure: O0rJCpkwbo0LcbPVbuGyS3JOVKUTvvOe/hf5tYpCjmF6kaSHTwKCmkMAIZAqNCu+RG2ur3BmfeBv2E8tsUP0YwfWopPpvGHRSoHeNfJpFefCFDi38Q931Go4an5mqSBCfxGDHT4k7OGQKQ3jLy1HKIFFViWXutheFJWaaqgZFsf7sVz+l02ZJ9bKdKxOKswS0yOmyiGrRVi/j1lDSyGWfaCYt9nG9ESJVqgtkTQ9tqzUrh78+fa4CwbJnToos2ZdyBAHoNkWyLIfmXRc9cCrVBcTs5mAaYuZ5k0jky5yQrNbUwBHEqM9OMn/M/LRsUGtkPmcNFWPbLzuY5c8BE6xIzGtKHpNR5ROgBoyQHavdMet/2zMLxchqEqKNHOO6pdno0RteSgyrxC/EcbHYxosIR0q+Aay9jKsqbQ8X9vlBEecVDx1+2qqrOm3FurKK3jKX3VwuzYAAwV54tfTUYW7K7c1k61Bs7M/LS1madby+Ic8zY5x4unGbH3s2KUbskEMyrlfnssrI82bdTUjp2weSSqF1p5m652prNQq64WA6jtoOpZP14gO/6pS1VHw/DbiqI3DUP19iyKjy06RMarT8RS27n4hUSES4KuZDlVPFJyROHQ2Y89LpWZETtFDoLKZ8vQRE7F4WtAFTVY4GANeZlMVKwt0tYkMJFioZnaxeSo=
    - secure: nj2huH1ENrt53+wRW2dnIVzBBVvl+dViKFn/e1GcmG1a200xcTRoqm+M9VIa2xePWXWOYQK1K1EJxXDuZ33oqcLNnnC7V605ItLADDhlheb7pJtTh6wSImZbE4cYxTVPNSWm1cNecwZW77ylVb06CLvCXtiNfm/1WobQqA8Q3173EzSixRimXgj7uDtAJqg8ObCmLYvmMyY0+O/FNZkqgU5nkt3ebf6dNg6ExUNCRl4aYoZ3SKkNQtEWV1F9K/nk4NCS7+Kuuf4RFY+1Di+Mv5YQJtOwEfHPWLrGCmaZLrxNqbGPjokdqL9kk4Ms6l79S8QA/Uwkf+HT2uNHbs9voyx1jLmuJTtuwW4RweKxl8oFbbsQ2loHOnEXDdl+CdnWproWkDtxUbxGxGVHocxASn/MDmlx1Yut/hMZbaTjFQ1ZzxYW66QLZRBj/8VlBfPiyvTwi1pOssemUD5uVFEuOjICTl0I+Jc6mxBVydzPeLVm1G5Y3olAot5vgsKVKC5PURND2xkRPFu9sTr4SueoMxszSymm6tOYmbClMqXt40/dGU6+QwCl5trWN/qXae5sSqbdtAb7UAROp2Or8cDstk2Z1fLfO4REwbsylVa0HYeKfxA9CtTCgWpFBJETOcGt/p4uWbTw2A+8ScOuAU5CLbK0PlmJR5EHh4WNkB0FeBI=
v35W6Nx5ckK6UvILiUwTj1JaY1pd1ZaGlUOz3jEp:
  secure: CoWMsFYs3dVTomb21vR869Nf9e4ozXmicY6HogXD8Aine+B1UP1Y2a+wGGhGed3i1+yIjr5cJtJ8Rg0k3OmP43bnNiQIO91+qWGXzfT/i+eN9Dju3ZtWPqcf+wkMJHXXdZpOk3gtLCDULMMMEOhzRbAtbIW9naSoKQv3OEsUjhT5gfGM0mnkd4Z8ZTaWAwyGcUIjIzIOdshh51VLL+ofmxNt2MiHx2WAos3zjNk4FjJPegEDD+aRIE5S25eeelYuk+ZFc/y07ysXG8T+/HjOu79/JIr9AQZD/AKR+yI0/ZiSpu32zvAao0bibLj3lYQpXDtXy8gAZfxfPbA961yGKz/gSjckaEAHl59dWWXQPo9rGWnoNIfOtqjT0T3GVRwh+BtX2scY/3npnCqSSFXm+vfdQUHHkkHCbPUD2wpnxtCnrl6Wk9GrvUI0Sf+tyxxM7sb8qmnGD0DNYZcWJl1im0PQzCTjeUMwZoDq4HjTBYb34PbueEt9bNZ9Fm+UuFIC/L+NmAb+cvRO5Otz6fn8EYYODFsgISlsPSxfkegf7AGuGnQIbHoO6crAy3163llOrr1ebtwlLRq5QKCDon7P0FlRSzvMrpZQEB25/IzX/idO4QM/mQi5BhN5R2zUzSCrKODSBTe5Dd1Sz2TlxHc4e5jD/R1smts7e/q9Qg3mPR8=
notifications:
  slack:
    secure: qHqIcGXhqUrprDck/cVKCBs0U6FQxtHVBsjF37bR/+AwohrWUnnoKLRN5BWg1q9TV91ADFbyWZDiSGDv+PZELGJalIL6i9NFvph5goJVG1kgnuHwwGCdcbLwy2rV7ShsWbXClC2iT+KXLTzmcUKYYaDvP5l/VOEiIQImQs4ErItoM3TvelRMLZVyhKQN5aT+tF86SkooFX2Lis/2p7mdNIhmHrNtnzd45424Ocu8lrAYUrSM2crskKp7wVhk7ycK1bMQMrmkWmrDrTWdGIyf7Vi/uGCBdeFp/3bR/zLAebTFibUw2IJG12FyF+F5MEgQHTnnHRNEn97wjcJRHI78U9Q4W/n3yxIEsZXx7wCPb/LQ3JNI3ooVioYq+0SUvLcPPcf16B++BDueBqyQ4v65PDA2+qHLW86GwiNOouleP7VtTPucXmo5dDKnWNdiysqN8paBUfnbdxuRIcw3ZMGro46Ckm6xIUuqVQXuPUQujdOcSnsna4AyGF1ldmToUiPC/i377sBg3av42iULAUrJIAIfKJZA6BbtEkIYEAJNYOIEZmPjEQJP0mI3OhY6sh3P4m0o5jyEvNRZmYejzGDpNWQkuFGLCaooYgE6mmNs9pZAhgaQ5WwjBwGBbhbY0rikjQkO5G9NDU50g0XycD3DLMCOj11XdkGEtsFzGlD1tzs=
