// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: approve_withdraw.proto

package forge_abi;

public final class ApproveWithdraw {
  private ApproveWithdraw() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApproveWithdrawTxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:forge_abi.ApproveWithdrawTx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the hash of withdraw tx
     * </pre>
     *
     * <code>string withdraw_tx_hash = 1;</code>
     */
    java.lang.String getWithdrawTxHash();
    /**
     * <pre>
     * the hash of withdraw tx
     * </pre>
     *
     * <code>string withdraw_tx_hash = 1;</code>
     */
    com.google.protobuf.ByteString
        getWithdrawTxHashBytes();

    /**
     * <pre>
     * the evidence of the original transaction that transferred the token back
     * </pre>
     *
     * <code>.forge_abi.Evidence evidence = 2;</code>
     */
    boolean hasEvidence();
    /**
     * <pre>
     * the evidence of the original transaction that transferred the token back
     * </pre>
     *
     * <code>.forge_abi.Evidence evidence = 2;</code>
     */
    forge_abi.Type.Evidence getEvidence();
    /**
     * <pre>
     * the evidence of the original transaction that transferred the token back
     * </pre>
     *
     * <code>.forge_abi.Evidence evidence = 2;</code>
     */
    forge_abi.Type.EvidenceOrBuilder getEvidenceOrBuilder();
  }
  /**
   * Protobuf type {@code forge_abi.ApproveWithdrawTx}
   */
  public  static final class ApproveWithdrawTx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:forge_abi.ApproveWithdrawTx)
      ApproveWithdrawTxOrBuilder {
    // Use ApproveWithdrawTx.newBuilder() to construct.
    private ApproveWithdrawTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApproveWithdrawTx() {
      withdrawTxHash_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApproveWithdrawTx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              withdrawTxHash_ = s;
              break;
            }
            case 18: {
              forge_abi.Type.Evidence.Builder subBuilder = null;
              if (evidence_ != null) {
                subBuilder = evidence_.toBuilder();
              }
              evidence_ = input.readMessage(forge_abi.Type.Evidence.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(evidence_);
                evidence_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forge_abi.ApproveWithdraw.internal_static_forge_abi_ApproveWithdrawTx_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forge_abi.ApproveWithdraw.internal_static_forge_abi_ApproveWithdrawTx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              forge_abi.ApproveWithdraw.ApproveWithdrawTx.class, forge_abi.ApproveWithdraw.ApproveWithdrawTx.Builder.class);
    }

    public static final int WITHDRAW_TX_HASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object withdrawTxHash_;
    /**
     * <pre>
     * the hash of withdraw tx
     * </pre>
     *
     * <code>string withdraw_tx_hash = 1;</code>
     */
    public java.lang.String getWithdrawTxHash() {
      java.lang.Object ref = withdrawTxHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        withdrawTxHash_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the hash of withdraw tx
     * </pre>
     *
     * <code>string withdraw_tx_hash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWithdrawTxHashBytes() {
      java.lang.Object ref = withdrawTxHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        withdrawTxHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVIDENCE_FIELD_NUMBER = 2;
    private forge_abi.Type.Evidence evidence_;
    /**
     * <pre>
     * the evidence of the original transaction that transferred the token back
     * </pre>
     *
     * <code>.forge_abi.Evidence evidence = 2;</code>
     */
    public boolean hasEvidence() {
      return evidence_ != null;
    }
    /**
     * <pre>
     * the evidence of the original transaction that transferred the token back
     * </pre>
     *
     * <code>.forge_abi.Evidence evidence = 2;</code>
     */
    public forge_abi.Type.Evidence getEvidence() {
      return evidence_ == null ? forge_abi.Type.Evidence.getDefaultInstance() : evidence_;
    }
    /**
     * <pre>
     * the evidence of the original transaction that transferred the token back
     * </pre>
     *
     * <code>.forge_abi.Evidence evidence = 2;</code>
     */
    public forge_abi.Type.EvidenceOrBuilder getEvidenceOrBuilder() {
      return getEvidence();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWithdrawTxHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, withdrawTxHash_);
      }
      if (evidence_ != null) {
        output.writeMessage(2, getEvidence());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWithdrawTxHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, withdrawTxHash_);
      }
      if (evidence_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEvidence());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof forge_abi.ApproveWithdraw.ApproveWithdrawTx)) {
        return super.equals(obj);
      }
      forge_abi.ApproveWithdraw.ApproveWithdrawTx other = (forge_abi.ApproveWithdraw.ApproveWithdrawTx) obj;

      boolean result = true;
      result = result && getWithdrawTxHash()
          .equals(other.getWithdrawTxHash());
      result = result && (hasEvidence() == other.hasEvidence());
      if (hasEvidence()) {
        result = result && getEvidence()
            .equals(other.getEvidence());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WITHDRAW_TX_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getWithdrawTxHash().hashCode();
      if (hasEvidence()) {
        hash = (37 * hash) + EVIDENCE_FIELD_NUMBER;
        hash = (53 * hash) + getEvidence().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(forge_abi.ApproveWithdraw.ApproveWithdrawTx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code forge_abi.ApproveWithdrawTx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:forge_abi.ApproveWithdrawTx)
        forge_abi.ApproveWithdraw.ApproveWithdrawTxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return forge_abi.ApproveWithdraw.internal_static_forge_abi_ApproveWithdrawTx_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return forge_abi.ApproveWithdraw.internal_static_forge_abi_ApproveWithdrawTx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                forge_abi.ApproveWithdraw.ApproveWithdrawTx.class, forge_abi.ApproveWithdraw.ApproveWithdrawTx.Builder.class);
      }

      // Construct using forge_abi.ApproveWithdraw.ApproveWithdrawTx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        withdrawTxHash_ = "";

        if (evidenceBuilder_ == null) {
          evidence_ = null;
        } else {
          evidence_ = null;
          evidenceBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return forge_abi.ApproveWithdraw.internal_static_forge_abi_ApproveWithdrawTx_descriptor;
      }

      public forge_abi.ApproveWithdraw.ApproveWithdrawTx getDefaultInstanceForType() {
        return forge_abi.ApproveWithdraw.ApproveWithdrawTx.getDefaultInstance();
      }

      public forge_abi.ApproveWithdraw.ApproveWithdrawTx build() {
        forge_abi.ApproveWithdraw.ApproveWithdrawTx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public forge_abi.ApproveWithdraw.ApproveWithdrawTx buildPartial() {
        forge_abi.ApproveWithdraw.ApproveWithdrawTx result = new forge_abi.ApproveWithdraw.ApproveWithdrawTx(this);
        result.withdrawTxHash_ = withdrawTxHash_;
        if (evidenceBuilder_ == null) {
          result.evidence_ = evidence_;
        } else {
          result.evidence_ = evidenceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof forge_abi.ApproveWithdraw.ApproveWithdrawTx) {
          return mergeFrom((forge_abi.ApproveWithdraw.ApproveWithdrawTx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(forge_abi.ApproveWithdraw.ApproveWithdrawTx other) {
        if (other == forge_abi.ApproveWithdraw.ApproveWithdrawTx.getDefaultInstance()) return this;
        if (!other.getWithdrawTxHash().isEmpty()) {
          withdrawTxHash_ = other.withdrawTxHash_;
          onChanged();
        }
        if (other.hasEvidence()) {
          mergeEvidence(other.getEvidence());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        forge_abi.ApproveWithdraw.ApproveWithdrawTx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (forge_abi.ApproveWithdraw.ApproveWithdrawTx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object withdrawTxHash_ = "";
      /**
       * <pre>
       * the hash of withdraw tx
       * </pre>
       *
       * <code>string withdraw_tx_hash = 1;</code>
       */
      public java.lang.String getWithdrawTxHash() {
        java.lang.Object ref = withdrawTxHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          withdrawTxHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the hash of withdraw tx
       * </pre>
       *
       * <code>string withdraw_tx_hash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWithdrawTxHashBytes() {
        java.lang.Object ref = withdrawTxHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          withdrawTxHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the hash of withdraw tx
       * </pre>
       *
       * <code>string withdraw_tx_hash = 1;</code>
       */
      public Builder setWithdrawTxHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        withdrawTxHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the hash of withdraw tx
       * </pre>
       *
       * <code>string withdraw_tx_hash = 1;</code>
       */
      public Builder clearWithdrawTxHash() {
        
        withdrawTxHash_ = getDefaultInstance().getWithdrawTxHash();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the hash of withdraw tx
       * </pre>
       *
       * <code>string withdraw_tx_hash = 1;</code>
       */
      public Builder setWithdrawTxHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        withdrawTxHash_ = value;
        onChanged();
        return this;
      }

      private forge_abi.Type.Evidence evidence_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          forge_abi.Type.Evidence, forge_abi.Type.Evidence.Builder, forge_abi.Type.EvidenceOrBuilder> evidenceBuilder_;
      /**
       * <pre>
       * the evidence of the original transaction that transferred the token back
       * </pre>
       *
       * <code>.forge_abi.Evidence evidence = 2;</code>
       */
      public boolean hasEvidence() {
        return evidenceBuilder_ != null || evidence_ != null;
      }
      /**
       * <pre>
       * the evidence of the original transaction that transferred the token back
       * </pre>
       *
       * <code>.forge_abi.Evidence evidence = 2;</code>
       */
      public forge_abi.Type.Evidence getEvidence() {
        if (evidenceBuilder_ == null) {
          return evidence_ == null ? forge_abi.Type.Evidence.getDefaultInstance() : evidence_;
        } else {
          return evidenceBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * the evidence of the original transaction that transferred the token back
       * </pre>
       *
       * <code>.forge_abi.Evidence evidence = 2;</code>
       */
      public Builder setEvidence(forge_abi.Type.Evidence value) {
        if (evidenceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          evidence_ = value;
          onChanged();
        } else {
          evidenceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * the evidence of the original transaction that transferred the token back
       * </pre>
       *
       * <code>.forge_abi.Evidence evidence = 2;</code>
       */
      public Builder setEvidence(
          forge_abi.Type.Evidence.Builder builderForValue) {
        if (evidenceBuilder_ == null) {
          evidence_ = builderForValue.build();
          onChanged();
        } else {
          evidenceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * the evidence of the original transaction that transferred the token back
       * </pre>
       *
       * <code>.forge_abi.Evidence evidence = 2;</code>
       */
      public Builder mergeEvidence(forge_abi.Type.Evidence value) {
        if (evidenceBuilder_ == null) {
          if (evidence_ != null) {
            evidence_ =
              forge_abi.Type.Evidence.newBuilder(evidence_).mergeFrom(value).buildPartial();
          } else {
            evidence_ = value;
          }
          onChanged();
        } else {
          evidenceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * the evidence of the original transaction that transferred the token back
       * </pre>
       *
       * <code>.forge_abi.Evidence evidence = 2;</code>
       */
      public Builder clearEvidence() {
        if (evidenceBuilder_ == null) {
          evidence_ = null;
          onChanged();
        } else {
          evidence_ = null;
          evidenceBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * the evidence of the original transaction that transferred the token back
       * </pre>
       *
       * <code>.forge_abi.Evidence evidence = 2;</code>
       */
      public forge_abi.Type.Evidence.Builder getEvidenceBuilder() {
        
        onChanged();
        return getEvidenceFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * the evidence of the original transaction that transferred the token back
       * </pre>
       *
       * <code>.forge_abi.Evidence evidence = 2;</code>
       */
      public forge_abi.Type.EvidenceOrBuilder getEvidenceOrBuilder() {
        if (evidenceBuilder_ != null) {
          return evidenceBuilder_.getMessageOrBuilder();
        } else {
          return evidence_ == null ?
              forge_abi.Type.Evidence.getDefaultInstance() : evidence_;
        }
      }
      /**
       * <pre>
       * the evidence of the original transaction that transferred the token back
       * </pre>
       *
       * <code>.forge_abi.Evidence evidence = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          forge_abi.Type.Evidence, forge_abi.Type.Evidence.Builder, forge_abi.Type.EvidenceOrBuilder> 
          getEvidenceFieldBuilder() {
        if (evidenceBuilder_ == null) {
          evidenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              forge_abi.Type.Evidence, forge_abi.Type.Evidence.Builder, forge_abi.Type.EvidenceOrBuilder>(
                  getEvidence(),
                  getParentForChildren(),
                  isClean());
          evidence_ = null;
        }
        return evidenceBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:forge_abi.ApproveWithdrawTx)
    }

    // @@protoc_insertion_point(class_scope:forge_abi.ApproveWithdrawTx)
    private static final forge_abi.ApproveWithdraw.ApproveWithdrawTx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new forge_abi.ApproveWithdraw.ApproveWithdrawTx();
    }

    public static forge_abi.ApproveWithdraw.ApproveWithdrawTx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApproveWithdrawTx>
        PARSER = new com.google.protobuf.AbstractParser<ApproveWithdrawTx>() {
      public ApproveWithdrawTx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApproveWithdrawTx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApproveWithdrawTx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApproveWithdrawTx> getParserForType() {
      return PARSER;
    }

    public forge_abi.ApproveWithdraw.ApproveWithdrawTx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forge_abi_ApproveWithdrawTx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forge_abi_ApproveWithdrawTx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026approve_withdraw.proto\022\tforge_abi\032\ntyp" +
      "e.proto\"T\n\021ApproveWithdrawTx\022\030\n\020withdraw" +
      "_tx_hash\030\001 \001(\t\022%\n\010evidence\030\002 \001(\0132\023.forge" +
      "_abi.Evidenceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          forge_abi.Type.getDescriptor(),
        }, assigner);
    internal_static_forge_abi_ApproveWithdrawTx_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_forge_abi_ApproveWithdrawTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forge_abi_ApproveWithdrawTx_descriptor,
        new java.lang.String[] { "WithdrawTxHash", "Evidence", });
    forge_abi.Type.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
