// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package forge_abi;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\tforge_abi\032\trpc.proto2\332\006" +
      "\n\010ChainRpc\022>\n\007send_tx\022\030.forge_abi.Reques" +
      "tSendTx\032\031.forge_abi.ResponseSendTx\022?\n\006ge" +
      "t_tx\022\027.forge_abi.RequestGetTx\032\030.forge_ab" +
      "i.ResponseGetTx(\0010\001\022H\n\tget_block\022\032.forge" +
      "_abi.RequestGetBlock\032\033.forge_abi.Respons" +
      "eGetBlock(\0010\001\022G\n\nget_blocks\022\033.forge_abi." +
      "RequestGetBlocks\032\034.forge_abi.ResponseGet" +
      "Blocks\022`\n\023get_unconfirmed_txs\022#.forge_ab" +
      "i.RequestGetUnconfirmedTxs\032$.forge_abi.R",
      "esponseGetUnconfirmedTxs\022Q\n\016get_chain_in" +
      "fo\022\036.forge_abi.RequestGetChainInfo\032\037.for" +
      "ge_abi.ResponseGetChainInfo\022N\n\rget_node_" +
      "info\022\035.forge_abi.RequestGetNodeInfo\032\036.fo" +
      "rge_abi.ResponseGetNodeInfo\022=\n\006search\022\030." +
      "forge_abi.RequestSearch\032\031.forge_abi.Resp" +
      "onseSearch\022K\n\014get_net_info\022\034.forge_abi.R" +
      "equestGetNetInfo\032\035.forge_abi.ResponseGet" +
      "NetInfo\022`\n\023get_validators_info\022#.forge_a" +
      "bi.RequestGetValidatorsInfo\032$.forge_abi.",
      "ResponseGetValidatorsInfo\022G\n\nget_config\022" +
      "\033.forge_abi.RequestGetConfig\032\034.forge_abi" +
      ".ResponseGetConfig2\242\001\n\010EventRpc\022H\n\tsubsc" +
      "ribe\022\033.forge_abi.RequestSubscribe\032\034.forg" +
      "e_abi.ResponseSubscribe0\001\022L\n\013unsubscribe" +
      "\022\035.forge_abi.RequestUnsubscribe\032\036.forge_" +
      "abi.ResponseUnsubscribe2\337\001\n\007FileRpc\022I\n\ns" +
      "tore_file\022\033.forge_abi.RequestStoreFile\032\034" +
      ".forge_abi.ResponseStoreFile(\001\022F\n\tload_f" +
      "ile\022\032.forge_abi.RequestLoadFile\032\033.forge_",
      "abi.ResponseLoadFile0\001\022A\n\010pin_file\022\031.for" +
      "ge_abi.RequestPinFile\032\032.forge_abi.Respon" +
      "sePinFile2\221\005\n\010StateRpc\022^\n\021get_account_st" +
      "ate\022!.forge_abi.RequestGetAccountState\032\"" +
      ".forge_abi.ResponseGetAccountState(\0010\001\022X" +
      "\n\017get_asset_state\022\037.forge_abi.RequestGet" +
      "AssetState\032 .forge_abi.ResponseGetAssetS" +
      "tate(\0010\001\022T\n\017get_forge_state\022\037.forge_abi." +
      "RequestGetForgeState\032 .forge_abi.Respons" +
      "eGetForgeState\022a\n\022get_protocol_state\022\".f",
      "orge_abi.RequestGetProtocolState\032#.forge" +
      "_abi.ResponseGetProtocolState(\0010\001\022X\n\017get" +
      "_stake_state\022\037.forge_abi.RequestGetStake" +
      "State\032 .forge_abi.ResponseGetStakeState(" +
      "\0010\001\022U\n\016get_swap_state\022\036.forge_abi.Reques" +
      "tGetSwapState\032\037.forge_abi.ResponseGetSwa" +
      "pState(\0010\001\022a\n\022get_delegate_state\022\".forge" +
      "_abi.RequestGetDelegateState\032#.forge_abi" +
      ".ResponseGetDelegateState(\0010\0012Z\n\tWalletR" +
      "pc\022M\n\014declare_node\022\035.forge_abi.RequestDe",
      "clareNode\032\036.forge_abi.ResponseDeclareNod" +
      "e2\335\006\n\010StatsRpc\022T\n\017get_forge_stats\022\037.forg" +
      "e_abi.RequestGetForgeStats\032 .forge_abi.R" +
      "esponseGetForgeStats\022\\\n\021list_transaction" +
      "s\022\".forge_abi.RequestListTransactions\032#." +
      "forge_abi.ResponseListTransactions\022J\n\013li" +
      "st_assets\022\034.forge_abi.RequestListAssets\032" +
      "\035.forge_abi.ResponseListAssets\022J\n\013list_s" +
      "takes\022\034.forge_abi.RequestListStakes\032\035.fo" +
      "rge_abi.ResponseListStakes\022M\n\014list_accou",
      "nt\022\035.forge_abi.RequestListAccount\032\036.forg" +
      "e_abi.ResponseListAccount\022Z\n\021list_top_ac" +
      "counts\022!.forge_abi.RequestListTopAccount" +
      "s\032\".forge_abi.ResponseListTopAccounts\022l\n" +
      "\027list_asset_transactions\022\'.forge_abi.Req" +
      "uestListAssetTransactions\032(.forge_abi.Re" +
      "sponseListAssetTransactions\022J\n\013list_bloc" +
      "ks\022\034.forge_abi.RequestListBlocks\032\035.forge" +
      "_abi.ResponseListBlocks\022Z\n\021get_health_st" +
      "atus\022!.forge_abi.RequestGetHealthStatus\032",
      "\".forge_abi.ResponseGetHealthStatus\022D\n\tl" +
      "ist_swap\022\032.forge_abi.RequestListSwap\032\033.f" +
      "orge_abi.ResponseListSwapb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          forge_abi.Rpc.getDescriptor(),
        }, assigner);
    forge_abi.Rpc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
