// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acquire_asset.proto

package forge_abi;

public final class AcquireAsset {
  private AcquireAsset() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AssetSpecOrBuilder extends
      // @@protoc_insertion_point(interface_extends:forge_abi.AssetSpec)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the address of the generated asset. The sender shall apply the spec to the
     * template to generate a structure of the asset, and then generate the
     * CreateAssetTx, and then calculate the address. SDK could help to alleviate
     * the process.
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    java.lang.String getAddress();
    /**
     * <pre>
     * the address of the generated asset. The sender shall apply the spec to the
     * template to generate a structure of the asset, and then generate the
     * CreateAssetTx, and then calculate the address. SDK could help to alleviate
     * the process.
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * json string that contains args for the asset factory template
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <pre>
     * json string that contains args for the asset factory template
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code forge_abi.AssetSpec}
   */
  public  static final class AssetSpec extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:forge_abi.AssetSpec)
      AssetSpecOrBuilder {
    // Use AssetSpec.newBuilder() to construct.
    private AssetSpec(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AssetSpec() {
      address_ = "";
      data_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AssetSpec(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forge_abi.AcquireAsset.internal_static_forge_abi_AssetSpec_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forge_abi.AcquireAsset.internal_static_forge_abi_AssetSpec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              forge_abi.AcquireAsset.AssetSpec.class, forge_abi.AcquireAsset.AssetSpec.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <pre>
     * the address of the generated asset. The sender shall apply the spec to the
     * template to generate a structure of the asset, and then generate the
     * CreateAssetTx, and then calculate the address. SDK could help to alleviate
     * the process.
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the address of the generated asset. The sender shall apply the spec to the
     * template to generate a structure of the asset, and then generate the
     * CreateAssetTx, and then calculate the address. SDK could help to alleviate
     * the process.
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object data_;
    /**
     * <pre>
     * json string that contains args for the asset factory template
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * json string that contains args for the asset factory template
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof forge_abi.AcquireAsset.AssetSpec)) {
        return super.equals(obj);
      }
      forge_abi.AcquireAsset.AssetSpec other = (forge_abi.AcquireAsset.AssetSpec) obj;

      boolean result = true;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static forge_abi.AcquireAsset.AssetSpec parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.AcquireAsset.AssetSpec parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.AcquireAsset.AssetSpec parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.AcquireAsset.AssetSpec parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.AcquireAsset.AssetSpec parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.AcquireAsset.AssetSpec parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.AcquireAsset.AssetSpec parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static forge_abi.AcquireAsset.AssetSpec parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.AcquireAsset.AssetSpec parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.AcquireAsset.AssetSpec parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(forge_abi.AcquireAsset.AssetSpec prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code forge_abi.AssetSpec}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:forge_abi.AssetSpec)
        forge_abi.AcquireAsset.AssetSpecOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return forge_abi.AcquireAsset.internal_static_forge_abi_AssetSpec_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return forge_abi.AcquireAsset.internal_static_forge_abi_AssetSpec_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                forge_abi.AcquireAsset.AssetSpec.class, forge_abi.AcquireAsset.AssetSpec.Builder.class);
      }

      // Construct using forge_abi.AcquireAsset.AssetSpec.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address_ = "";

        data_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return forge_abi.AcquireAsset.internal_static_forge_abi_AssetSpec_descriptor;
      }

      public forge_abi.AcquireAsset.AssetSpec getDefaultInstanceForType() {
        return forge_abi.AcquireAsset.AssetSpec.getDefaultInstance();
      }

      public forge_abi.AcquireAsset.AssetSpec build() {
        forge_abi.AcquireAsset.AssetSpec result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public forge_abi.AcquireAsset.AssetSpec buildPartial() {
        forge_abi.AcquireAsset.AssetSpec result = new forge_abi.AcquireAsset.AssetSpec(this);
        result.address_ = address_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof forge_abi.AcquireAsset.AssetSpec) {
          return mergeFrom((forge_abi.AcquireAsset.AssetSpec)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(forge_abi.AcquireAsset.AssetSpec other) {
        if (other == forge_abi.AcquireAsset.AssetSpec.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        forge_abi.AcquireAsset.AssetSpec parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (forge_abi.AcquireAsset.AssetSpec) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       * the address of the generated asset. The sender shall apply the spec to the
       * template to generate a structure of the asset, and then generate the
       * CreateAssetTx, and then calculate the address. SDK could help to alleviate
       * the process.
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the address of the generated asset. The sender shall apply the spec to the
       * template to generate a structure of the asset, and then generate the
       * CreateAssetTx, and then calculate the address. SDK could help to alleviate
       * the process.
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the address of the generated asset. The sender shall apply the spec to the
       * template to generate a structure of the asset, and then generate the
       * CreateAssetTx, and then calculate the address. SDK could help to alleviate
       * the process.
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the address of the generated asset. The sender shall apply the spec to the
       * template to generate a structure of the asset, and then generate the
       * CreateAssetTx, and then calculate the address. SDK could help to alleviate
       * the process.
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the address of the generated asset. The sender shall apply the spec to the
       * template to generate a structure of the asset, and then generate the
       * CreateAssetTx, and then calculate the address. SDK could help to alleviate
       * the process.
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       * json string that contains args for the asset factory template
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * json string that contains args for the asset factory template
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * json string that contains args for the asset factory template
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * json string that contains args for the asset factory template
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * json string that contains args for the asset factory template
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:forge_abi.AssetSpec)
    }

    // @@protoc_insertion_point(class_scope:forge_abi.AssetSpec)
    private static final forge_abi.AcquireAsset.AssetSpec DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new forge_abi.AcquireAsset.AssetSpec();
    }

    public static forge_abi.AcquireAsset.AssetSpec getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AssetSpec>
        PARSER = new com.google.protobuf.AbstractParser<AssetSpec>() {
      public AssetSpec parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AssetSpec(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AssetSpec> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AssetSpec> getParserForType() {
      return PARSER;
    }

    public forge_abi.AcquireAsset.AssetSpec getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AcquireAssetTxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:forge_abi.AcquireAssetTx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the address of the asset factory
     * </pre>
     *
     * <code>string to = 1;</code>
     */
    java.lang.String getTo();
    /**
     * <pre>
     * the address of the asset factory
     * </pre>
     *
     * <code>string to = 1;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     * asset spec
     * </pre>
     *
     * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
     */
    java.util.List<forge_abi.AcquireAsset.AssetSpec> 
        getSpecsList();
    /**
     * <pre>
     * asset spec
     * </pre>
     *
     * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
     */
    forge_abi.AcquireAsset.AssetSpec getSpecs(int index);
    /**
     * <pre>
     * asset spec
     * </pre>
     *
     * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
     */
    int getSpecsCount();
    /**
     * <pre>
     * asset spec
     * </pre>
     *
     * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
     */
    java.util.List<? extends forge_abi.AcquireAsset.AssetSpecOrBuilder> 
        getSpecsOrBuilderList();
    /**
     * <pre>
     * asset spec
     * </pre>
     *
     * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
     */
    forge_abi.AcquireAsset.AssetSpecOrBuilder getSpecsOrBuilder(
        int index);

    /**
     * <pre>
     * forge won't touch this field. Only forge app shall handle it.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 15;</code>
     */
    boolean hasData();
    /**
     * <pre>
     * forge won't touch this field. Only forge app shall handle it.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 15;</code>
     */
    com.google.protobuf.Any getData();
    /**
     * <pre>
     * forge won't touch this field. Only forge app shall handle it.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 15;</code>
     */
    com.google.protobuf.AnyOrBuilder getDataOrBuilder();
  }
  /**
   * Protobuf type {@code forge_abi.AcquireAssetTx}
   */
  public  static final class AcquireAssetTx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:forge_abi.AcquireAssetTx)
      AcquireAssetTxOrBuilder {
    // Use AcquireAssetTx.newBuilder() to construct.
    private AcquireAssetTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AcquireAssetTx() {
      to_ = "";
      specs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AcquireAssetTx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                specs_ = new java.util.ArrayList<forge_abi.AcquireAsset.AssetSpec>();
                mutable_bitField0_ |= 0x00000002;
              }
              specs_.add(
                  input.readMessage(forge_abi.AcquireAsset.AssetSpec.parser(), extensionRegistry));
              break;
            }
            case 122: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          specs_ = java.util.Collections.unmodifiableList(specs_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forge_abi.AcquireAsset.internal_static_forge_abi_AcquireAssetTx_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forge_abi.AcquireAsset.internal_static_forge_abi_AcquireAssetTx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              forge_abi.AcquireAsset.AcquireAssetTx.class, forge_abi.AcquireAsset.AcquireAssetTx.Builder.class);
    }

    private int bitField0_;
    public static final int TO_FIELD_NUMBER = 1;
    private volatile java.lang.Object to_;
    /**
     * <pre>
     * the address of the asset factory
     * </pre>
     *
     * <code>string to = 1;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the address of the asset factory
     * </pre>
     *
     * <code>string to = 1;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPECS_FIELD_NUMBER = 2;
    private java.util.List<forge_abi.AcquireAsset.AssetSpec> specs_;
    /**
     * <pre>
     * asset spec
     * </pre>
     *
     * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
     */
    public java.util.List<forge_abi.AcquireAsset.AssetSpec> getSpecsList() {
      return specs_;
    }
    /**
     * <pre>
     * asset spec
     * </pre>
     *
     * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
     */
    public java.util.List<? extends forge_abi.AcquireAsset.AssetSpecOrBuilder> 
        getSpecsOrBuilderList() {
      return specs_;
    }
    /**
     * <pre>
     * asset spec
     * </pre>
     *
     * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
     */
    public int getSpecsCount() {
      return specs_.size();
    }
    /**
     * <pre>
     * asset spec
     * </pre>
     *
     * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
     */
    public forge_abi.AcquireAsset.AssetSpec getSpecs(int index) {
      return specs_.get(index);
    }
    /**
     * <pre>
     * asset spec
     * </pre>
     *
     * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
     */
    public forge_abi.AcquireAsset.AssetSpecOrBuilder getSpecsOrBuilder(
        int index) {
      return specs_.get(index);
    }

    public static final int DATA_FIELD_NUMBER = 15;
    private com.google.protobuf.Any data_;
    /**
     * <pre>
     * forge won't touch this field. Only forge app shall handle it.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 15;</code>
     */
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <pre>
     * forge won't touch this field. Only forge app shall handle it.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 15;</code>
     */
    public com.google.protobuf.Any getData() {
      return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
    }
    /**
     * <pre>
     * forge won't touch this field. Only forge app shall handle it.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 15;</code>
     */
    public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
      return getData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, to_);
      }
      for (int i = 0; i < specs_.size(); i++) {
        output.writeMessage(2, specs_.get(i));
      }
      if (data_ != null) {
        output.writeMessage(15, getData());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, to_);
      }
      for (int i = 0; i < specs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, specs_.get(i));
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getData());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof forge_abi.AcquireAsset.AcquireAssetTx)) {
        return super.equals(obj);
      }
      forge_abi.AcquireAsset.AcquireAssetTx other = (forge_abi.AcquireAsset.AcquireAssetTx) obj;

      boolean result = true;
      result = result && getTo()
          .equals(other.getTo());
      result = result && getSpecsList()
          .equals(other.getSpecsList());
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      if (getSpecsCount() > 0) {
        hash = (37 * hash) + SPECS_FIELD_NUMBER;
        hash = (53 * hash) + getSpecsList().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static forge_abi.AcquireAsset.AcquireAssetTx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.AcquireAsset.AcquireAssetTx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.AcquireAsset.AcquireAssetTx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.AcquireAsset.AcquireAssetTx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.AcquireAsset.AcquireAssetTx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.AcquireAsset.AcquireAssetTx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.AcquireAsset.AcquireAssetTx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static forge_abi.AcquireAsset.AcquireAssetTx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.AcquireAsset.AcquireAssetTx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.AcquireAsset.AcquireAssetTx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(forge_abi.AcquireAsset.AcquireAssetTx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code forge_abi.AcquireAssetTx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:forge_abi.AcquireAssetTx)
        forge_abi.AcquireAsset.AcquireAssetTxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return forge_abi.AcquireAsset.internal_static_forge_abi_AcquireAssetTx_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return forge_abi.AcquireAsset.internal_static_forge_abi_AcquireAssetTx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                forge_abi.AcquireAsset.AcquireAssetTx.class, forge_abi.AcquireAsset.AcquireAssetTx.Builder.class);
      }

      // Construct using forge_abi.AcquireAsset.AcquireAssetTx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSpecsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        to_ = "";

        if (specsBuilder_ == null) {
          specs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          specsBuilder_.clear();
        }
        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return forge_abi.AcquireAsset.internal_static_forge_abi_AcquireAssetTx_descriptor;
      }

      public forge_abi.AcquireAsset.AcquireAssetTx getDefaultInstanceForType() {
        return forge_abi.AcquireAsset.AcquireAssetTx.getDefaultInstance();
      }

      public forge_abi.AcquireAsset.AcquireAssetTx build() {
        forge_abi.AcquireAsset.AcquireAssetTx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public forge_abi.AcquireAsset.AcquireAssetTx buildPartial() {
        forge_abi.AcquireAsset.AcquireAssetTx result = new forge_abi.AcquireAsset.AcquireAssetTx(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.to_ = to_;
        if (specsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            specs_ = java.util.Collections.unmodifiableList(specs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.specs_ = specs_;
        } else {
          result.specs_ = specsBuilder_.build();
        }
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof forge_abi.AcquireAsset.AcquireAssetTx) {
          return mergeFrom((forge_abi.AcquireAsset.AcquireAssetTx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(forge_abi.AcquireAsset.AcquireAssetTx other) {
        if (other == forge_abi.AcquireAsset.AcquireAssetTx.getDefaultInstance()) return this;
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (specsBuilder_ == null) {
          if (!other.specs_.isEmpty()) {
            if (specs_.isEmpty()) {
              specs_ = other.specs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSpecsIsMutable();
              specs_.addAll(other.specs_);
            }
            onChanged();
          }
        } else {
          if (!other.specs_.isEmpty()) {
            if (specsBuilder_.isEmpty()) {
              specsBuilder_.dispose();
              specsBuilder_ = null;
              specs_ = other.specs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              specsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSpecsFieldBuilder() : null;
            } else {
              specsBuilder_.addAllMessages(other.specs_);
            }
          }
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        forge_abi.AcquireAsset.AcquireAssetTx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (forge_abi.AcquireAsset.AcquireAssetTx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object to_ = "";
      /**
       * <pre>
       * the address of the asset factory
       * </pre>
       *
       * <code>string to = 1;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the address of the asset factory
       * </pre>
       *
       * <code>string to = 1;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the address of the asset factory
       * </pre>
       *
       * <code>string to = 1;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the address of the asset factory
       * </pre>
       *
       * <code>string to = 1;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the address of the asset factory
       * </pre>
       *
       * <code>string to = 1;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private java.util.List<forge_abi.AcquireAsset.AssetSpec> specs_ =
        java.util.Collections.emptyList();
      private void ensureSpecsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          specs_ = new java.util.ArrayList<forge_abi.AcquireAsset.AssetSpec>(specs_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          forge_abi.AcquireAsset.AssetSpec, forge_abi.AcquireAsset.AssetSpec.Builder, forge_abi.AcquireAsset.AssetSpecOrBuilder> specsBuilder_;

      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public java.util.List<forge_abi.AcquireAsset.AssetSpec> getSpecsList() {
        if (specsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(specs_);
        } else {
          return specsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public int getSpecsCount() {
        if (specsBuilder_ == null) {
          return specs_.size();
        } else {
          return specsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public forge_abi.AcquireAsset.AssetSpec getSpecs(int index) {
        if (specsBuilder_ == null) {
          return specs_.get(index);
        } else {
          return specsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public Builder setSpecs(
          int index, forge_abi.AcquireAsset.AssetSpec value) {
        if (specsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSpecsIsMutable();
          specs_.set(index, value);
          onChanged();
        } else {
          specsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public Builder setSpecs(
          int index, forge_abi.AcquireAsset.AssetSpec.Builder builderForValue) {
        if (specsBuilder_ == null) {
          ensureSpecsIsMutable();
          specs_.set(index, builderForValue.build());
          onChanged();
        } else {
          specsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public Builder addSpecs(forge_abi.AcquireAsset.AssetSpec value) {
        if (specsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSpecsIsMutable();
          specs_.add(value);
          onChanged();
        } else {
          specsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public Builder addSpecs(
          int index, forge_abi.AcquireAsset.AssetSpec value) {
        if (specsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSpecsIsMutable();
          specs_.add(index, value);
          onChanged();
        } else {
          specsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public Builder addSpecs(
          forge_abi.AcquireAsset.AssetSpec.Builder builderForValue) {
        if (specsBuilder_ == null) {
          ensureSpecsIsMutable();
          specs_.add(builderForValue.build());
          onChanged();
        } else {
          specsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public Builder addSpecs(
          int index, forge_abi.AcquireAsset.AssetSpec.Builder builderForValue) {
        if (specsBuilder_ == null) {
          ensureSpecsIsMutable();
          specs_.add(index, builderForValue.build());
          onChanged();
        } else {
          specsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public Builder addAllSpecs(
          java.lang.Iterable<? extends forge_abi.AcquireAsset.AssetSpec> values) {
        if (specsBuilder_ == null) {
          ensureSpecsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, specs_);
          onChanged();
        } else {
          specsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public Builder clearSpecs() {
        if (specsBuilder_ == null) {
          specs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          specsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public Builder removeSpecs(int index) {
        if (specsBuilder_ == null) {
          ensureSpecsIsMutable();
          specs_.remove(index);
          onChanged();
        } else {
          specsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public forge_abi.AcquireAsset.AssetSpec.Builder getSpecsBuilder(
          int index) {
        return getSpecsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public forge_abi.AcquireAsset.AssetSpecOrBuilder getSpecsOrBuilder(
          int index) {
        if (specsBuilder_ == null) {
          return specs_.get(index);  } else {
          return specsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public java.util.List<? extends forge_abi.AcquireAsset.AssetSpecOrBuilder> 
           getSpecsOrBuilderList() {
        if (specsBuilder_ != null) {
          return specsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(specs_);
        }
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public forge_abi.AcquireAsset.AssetSpec.Builder addSpecsBuilder() {
        return getSpecsFieldBuilder().addBuilder(
            forge_abi.AcquireAsset.AssetSpec.getDefaultInstance());
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public forge_abi.AcquireAsset.AssetSpec.Builder addSpecsBuilder(
          int index) {
        return getSpecsFieldBuilder().addBuilder(
            index, forge_abi.AcquireAsset.AssetSpec.getDefaultInstance());
      }
      /**
       * <pre>
       * asset spec
       * </pre>
       *
       * <code>repeated .forge_abi.AssetSpec specs = 2;</code>
       */
      public java.util.List<forge_abi.AcquireAsset.AssetSpec.Builder> 
           getSpecsBuilderList() {
        return getSpecsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          forge_abi.AcquireAsset.AssetSpec, forge_abi.AcquireAsset.AssetSpec.Builder, forge_abi.AcquireAsset.AssetSpecOrBuilder> 
          getSpecsFieldBuilder() {
        if (specsBuilder_ == null) {
          specsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              forge_abi.AcquireAsset.AssetSpec, forge_abi.AcquireAsset.AssetSpec.Builder, forge_abi.AcquireAsset.AssetSpecOrBuilder>(
                  specs_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          specs_ = null;
        }
        return specsBuilder_;
      }

      private com.google.protobuf.Any data_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;
      /**
       * <pre>
       * forge won't touch this field. Only forge app shall handle it.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <pre>
       * forge won't touch this field. Only forge app shall handle it.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public com.google.protobuf.Any getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * forge won't touch this field. Only forge app shall handle it.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public Builder setData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * forge won't touch this field. Only forge app shall handle it.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public Builder setData(
          com.google.protobuf.Any.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * forge won't touch this field. Only forge app shall handle it.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public Builder mergeData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * forge won't touch this field. Only forge app shall handle it.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * forge won't touch this field. Only forge app shall handle it.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public com.google.protobuf.Any.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * forge won't touch this field. Only forge app shall handle it.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : data_;
        }
      }
      /**
       * <pre>
       * forge won't touch this field. Only forge app shall handle it.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 15;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:forge_abi.AcquireAssetTx)
    }

    // @@protoc_insertion_point(class_scope:forge_abi.AcquireAssetTx)
    private static final forge_abi.AcquireAsset.AcquireAssetTx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new forge_abi.AcquireAsset.AcquireAssetTx();
    }

    public static forge_abi.AcquireAsset.AcquireAssetTx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AcquireAssetTx>
        PARSER = new com.google.protobuf.AbstractParser<AcquireAssetTx>() {
      public AcquireAssetTx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AcquireAssetTx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AcquireAssetTx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AcquireAssetTx> getParserForType() {
      return PARSER;
    }

    public forge_abi.AcquireAsset.AcquireAssetTx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forge_abi_AssetSpec_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forge_abi_AssetSpec_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forge_abi_AcquireAssetTx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forge_abi_AcquireAssetTx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023acquire_asset.proto\022\tforge_abi\032\031google" +
      "/protobuf/any.proto\"*\n\tAssetSpec\022\017\n\007addr" +
      "ess\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\"e\n\016AcquireAssetT" +
      "x\022\n\n\002to\030\001 \001(\t\022#\n\005specs\030\002 \003(\0132\024.forge_abi" +
      ".AssetSpec\022\"\n\004data\030\017 \001(\0132\024.google.protob" +
      "uf.Anyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_forge_abi_AssetSpec_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_forge_abi_AssetSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forge_abi_AssetSpec_descriptor,
        new java.lang.String[] { "Address", "Data", });
    internal_static_forge_abi_AcquireAssetTx_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_forge_abi_AcquireAssetTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forge_abi_AcquireAssetTx_descriptor,
        new java.lang.String[] { "To", "Specs", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
