// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_asset.proto

package forge_abi;

public final class CreateAsset {
  private CreateAsset() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateAssetTxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:forge_abi.CreateAssetTx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string moniker = 1;</code>
     */
    java.lang.String getMoniker();
    /**
     * <code>string moniker = 1;</code>
     */
    com.google.protobuf.ByteString
        getMonikerBytes();

    /**
     * <pre>
     * forge won't update data into state if app is interested in this tx.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    boolean hasData();
    /**
     * <pre>
     * forge won't update data into state if app is interested in this tx.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    com.google.protobuf.Any getData();
    /**
     * <pre>
     * forge won't update data into state if app is interested in this tx.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getDataOrBuilder();

    /**
     * <code>bool readonly = 3;</code>
     */
    boolean getReadonly();

    /**
     * <code>bool transferrable = 4;</code>
     */
    boolean getTransferrable();

    /**
     * <pre>
     * ttl for the asset after first consumption. 0 means unlimited.
     * </pre>
     *
     * <code>uint32 ttl = 5;</code>
     */
    int getTtl();

    /**
     * <code>string parent = 6;</code>
     */
    java.lang.String getParent();
    /**
     * <code>string parent = 6;</code>
     */
    com.google.protobuf.ByteString
        getParentBytes();

    /**
     * <pre>
     * asset address
     * </pre>
     *
     * <code>string address = 7;</code>
     */
    java.lang.String getAddress();
    /**
     * <pre>
     * asset address
     * </pre>
     *
     * <code>string address = 7;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code forge_abi.CreateAssetTx}
   */
  public  static final class CreateAssetTx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:forge_abi.CreateAssetTx)
      CreateAssetTxOrBuilder {
    // Use CreateAssetTx.newBuilder() to construct.
    private CreateAssetTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateAssetTx() {
      moniker_ = "";
      readonly_ = false;
      transferrable_ = false;
      ttl_ = 0;
      parent_ = "";
      address_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CreateAssetTx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              moniker_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              readonly_ = input.readBool();
              break;
            }
            case 32: {

              transferrable_ = input.readBool();
              break;
            }
            case 40: {

              ttl_ = input.readUInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              parent_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forge_abi.CreateAsset.internal_static_forge_abi_CreateAssetTx_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forge_abi.CreateAsset.internal_static_forge_abi_CreateAssetTx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              forge_abi.CreateAsset.CreateAssetTx.class, forge_abi.CreateAsset.CreateAssetTx.Builder.class);
    }

    public static final int MONIKER_FIELD_NUMBER = 1;
    private volatile java.lang.Object moniker_;
    /**
     * <code>string moniker = 1;</code>
     */
    public java.lang.String getMoniker() {
      java.lang.Object ref = moniker_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        moniker_ = s;
        return s;
      }
    }
    /**
     * <code>string moniker = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMonikerBytes() {
      java.lang.Object ref = moniker_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moniker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.Any data_;
    /**
     * <pre>
     * forge won't update data into state if app is interested in this tx.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <pre>
     * forge won't update data into state if app is interested in this tx.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public com.google.protobuf.Any getData() {
      return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
    }
    /**
     * <pre>
     * forge won't update data into state if app is interested in this tx.
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
      return getData();
    }

    public static final int READONLY_FIELD_NUMBER = 3;
    private boolean readonly_;
    /**
     * <code>bool readonly = 3;</code>
     */
    public boolean getReadonly() {
      return readonly_;
    }

    public static final int TRANSFERRABLE_FIELD_NUMBER = 4;
    private boolean transferrable_;
    /**
     * <code>bool transferrable = 4;</code>
     */
    public boolean getTransferrable() {
      return transferrable_;
    }

    public static final int TTL_FIELD_NUMBER = 5;
    private int ttl_;
    /**
     * <pre>
     * ttl for the asset after first consumption. 0 means unlimited.
     * </pre>
     *
     * <code>uint32 ttl = 5;</code>
     */
    public int getTtl() {
      return ttl_;
    }

    public static final int PARENT_FIELD_NUMBER = 6;
    private volatile java.lang.Object parent_;
    /**
     * <code>string parent = 6;</code>
     */
    public java.lang.String getParent() {
      java.lang.Object ref = parent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parent_ = s;
        return s;
      }
    }
    /**
     * <code>string parent = 6;</code>
     */
    public com.google.protobuf.ByteString
        getParentBytes() {
      java.lang.Object ref = parent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 7;
    private volatile java.lang.Object address_;
    /**
     * <pre>
     * asset address
     * </pre>
     *
     * <code>string address = 7;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * asset address
     * </pre>
     *
     * <code>string address = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMonikerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, moniker_);
      }
      if (data_ != null) {
        output.writeMessage(2, getData());
      }
      if (readonly_ != false) {
        output.writeBool(3, readonly_);
      }
      if (transferrable_ != false) {
        output.writeBool(4, transferrable_);
      }
      if (ttl_ != 0) {
        output.writeUInt32(5, ttl_);
      }
      if (!getParentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, parent_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, address_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMonikerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, moniker_);
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getData());
      }
      if (readonly_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, readonly_);
      }
      if (transferrable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, transferrable_);
      }
      if (ttl_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, ttl_);
      }
      if (!getParentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, parent_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, address_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof forge_abi.CreateAsset.CreateAssetTx)) {
        return super.equals(obj);
      }
      forge_abi.CreateAsset.CreateAssetTx other = (forge_abi.CreateAsset.CreateAssetTx) obj;

      boolean result = true;
      result = result && getMoniker()
          .equals(other.getMoniker());
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && (getReadonly()
          == other.getReadonly());
      result = result && (getTransferrable()
          == other.getTransferrable());
      result = result && (getTtl()
          == other.getTtl());
      result = result && getParent()
          .equals(other.getParent());
      result = result && getAddress()
          .equals(other.getAddress());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MONIKER_FIELD_NUMBER;
      hash = (53 * hash) + getMoniker().hashCode();
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (37 * hash) + READONLY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getReadonly());
      hash = (37 * hash) + TRANSFERRABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTransferrable());
      hash = (37 * hash) + TTL_FIELD_NUMBER;
      hash = (53 * hash) + getTtl();
      hash = (37 * hash) + PARENT_FIELD_NUMBER;
      hash = (53 * hash) + getParent().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static forge_abi.CreateAsset.CreateAssetTx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.CreateAsset.CreateAssetTx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.CreateAsset.CreateAssetTx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.CreateAsset.CreateAssetTx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.CreateAsset.CreateAssetTx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.CreateAsset.CreateAssetTx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.CreateAsset.CreateAssetTx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static forge_abi.CreateAsset.CreateAssetTx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.CreateAsset.CreateAssetTx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.CreateAsset.CreateAssetTx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(forge_abi.CreateAsset.CreateAssetTx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code forge_abi.CreateAssetTx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:forge_abi.CreateAssetTx)
        forge_abi.CreateAsset.CreateAssetTxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return forge_abi.CreateAsset.internal_static_forge_abi_CreateAssetTx_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return forge_abi.CreateAsset.internal_static_forge_abi_CreateAssetTx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                forge_abi.CreateAsset.CreateAssetTx.class, forge_abi.CreateAsset.CreateAssetTx.Builder.class);
      }

      // Construct using forge_abi.CreateAsset.CreateAssetTx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        moniker_ = "";

        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        readonly_ = false;

        transferrable_ = false;

        ttl_ = 0;

        parent_ = "";

        address_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return forge_abi.CreateAsset.internal_static_forge_abi_CreateAssetTx_descriptor;
      }

      public forge_abi.CreateAsset.CreateAssetTx getDefaultInstanceForType() {
        return forge_abi.CreateAsset.CreateAssetTx.getDefaultInstance();
      }

      public forge_abi.CreateAsset.CreateAssetTx build() {
        forge_abi.CreateAsset.CreateAssetTx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public forge_abi.CreateAsset.CreateAssetTx buildPartial() {
        forge_abi.CreateAsset.CreateAssetTx result = new forge_abi.CreateAsset.CreateAssetTx(this);
        result.moniker_ = moniker_;
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.readonly_ = readonly_;
        result.transferrable_ = transferrable_;
        result.ttl_ = ttl_;
        result.parent_ = parent_;
        result.address_ = address_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof forge_abi.CreateAsset.CreateAssetTx) {
          return mergeFrom((forge_abi.CreateAsset.CreateAssetTx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(forge_abi.CreateAsset.CreateAssetTx other) {
        if (other == forge_abi.CreateAsset.CreateAssetTx.getDefaultInstance()) return this;
        if (!other.getMoniker().isEmpty()) {
          moniker_ = other.moniker_;
          onChanged();
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        if (other.getReadonly() != false) {
          setReadonly(other.getReadonly());
        }
        if (other.getTransferrable() != false) {
          setTransferrable(other.getTransferrable());
        }
        if (other.getTtl() != 0) {
          setTtl(other.getTtl());
        }
        if (!other.getParent().isEmpty()) {
          parent_ = other.parent_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        forge_abi.CreateAsset.CreateAssetTx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (forge_abi.CreateAsset.CreateAssetTx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object moniker_ = "";
      /**
       * <code>string moniker = 1;</code>
       */
      public java.lang.String getMoniker() {
        java.lang.Object ref = moniker_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          moniker_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string moniker = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMonikerBytes() {
        java.lang.Object ref = moniker_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          moniker_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string moniker = 1;</code>
       */
      public Builder setMoniker(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        moniker_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string moniker = 1;</code>
       */
      public Builder clearMoniker() {
        
        moniker_ = getDefaultInstance().getMoniker();
        onChanged();
        return this;
      }
      /**
       * <code>string moniker = 1;</code>
       */
      public Builder setMonikerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        moniker_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any data_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;
      /**
       * <pre>
       * forge won't update data into state if app is interested in this tx.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <pre>
       * forge won't update data into state if app is interested in this tx.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public com.google.protobuf.Any getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * forge won't update data into state if app is interested in this tx.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public Builder setData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * forge won't update data into state if app is interested in this tx.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public Builder setData(
          com.google.protobuf.Any.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * forge won't update data into state if app is interested in this tx.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public Builder mergeData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * forge won't update data into state if app is interested in this tx.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * forge won't update data into state if app is interested in this tx.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public com.google.protobuf.Any.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * forge won't update data into state if app is interested in this tx.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : data_;
        }
      }
      /**
       * <pre>
       * forge won't update data into state if app is interested in this tx.
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      private boolean readonly_ ;
      /**
       * <code>bool readonly = 3;</code>
       */
      public boolean getReadonly() {
        return readonly_;
      }
      /**
       * <code>bool readonly = 3;</code>
       */
      public Builder setReadonly(boolean value) {
        
        readonly_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool readonly = 3;</code>
       */
      public Builder clearReadonly() {
        
        readonly_ = false;
        onChanged();
        return this;
      }

      private boolean transferrable_ ;
      /**
       * <code>bool transferrable = 4;</code>
       */
      public boolean getTransferrable() {
        return transferrable_;
      }
      /**
       * <code>bool transferrable = 4;</code>
       */
      public Builder setTransferrable(boolean value) {
        
        transferrable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool transferrable = 4;</code>
       */
      public Builder clearTransferrable() {
        
        transferrable_ = false;
        onChanged();
        return this;
      }

      private int ttl_ ;
      /**
       * <pre>
       * ttl for the asset after first consumption. 0 means unlimited.
       * </pre>
       *
       * <code>uint32 ttl = 5;</code>
       */
      public int getTtl() {
        return ttl_;
      }
      /**
       * <pre>
       * ttl for the asset after first consumption. 0 means unlimited.
       * </pre>
       *
       * <code>uint32 ttl = 5;</code>
       */
      public Builder setTtl(int value) {
        
        ttl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ttl for the asset after first consumption. 0 means unlimited.
       * </pre>
       *
       * <code>uint32 ttl = 5;</code>
       */
      public Builder clearTtl() {
        
        ttl_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object parent_ = "";
      /**
       * <code>string parent = 6;</code>
       */
      public java.lang.String getParent() {
        java.lang.Object ref = parent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          parent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string parent = 6;</code>
       */
      public com.google.protobuf.ByteString
          getParentBytes() {
        java.lang.Object ref = parent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string parent = 6;</code>
       */
      public Builder setParent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string parent = 6;</code>
       */
      public Builder clearParent() {
        
        parent_ = getDefaultInstance().getParent();
        onChanged();
        return this;
      }
      /**
       * <code>string parent = 6;</code>
       */
      public Builder setParentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        parent_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       * asset address
       * </pre>
       *
       * <code>string address = 7;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * asset address
       * </pre>
       *
       * <code>string address = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * asset address
       * </pre>
       *
       * <code>string address = 7;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * asset address
       * </pre>
       *
       * <code>string address = 7;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * asset address
       * </pre>
       *
       * <code>string address = 7;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:forge_abi.CreateAssetTx)
    }

    // @@protoc_insertion_point(class_scope:forge_abi.CreateAssetTx)
    private static final forge_abi.CreateAsset.CreateAssetTx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new forge_abi.CreateAsset.CreateAssetTx();
    }

    public static forge_abi.CreateAsset.CreateAssetTx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateAssetTx>
        PARSER = new com.google.protobuf.AbstractParser<CreateAssetTx>() {
      public CreateAssetTx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CreateAssetTx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateAssetTx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateAssetTx> getParserForType() {
      return PARSER;
    }

    public forge_abi.CreateAsset.CreateAssetTx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forge_abi_CreateAssetTx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forge_abi_CreateAssetTx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022create_asset.proto\022\tforge_abi\032\031google/" +
      "protobuf/any.proto\"\233\001\n\rCreateAssetTx\022\017\n\007" +
      "moniker\030\001 \001(\t\022\"\n\004data\030\002 \001(\0132\024.google.pro" +
      "tobuf.Any\022\020\n\010readonly\030\003 \001(\010\022\025\n\rtransferr" +
      "able\030\004 \001(\010\022\013\n\003ttl\030\005 \001(\r\022\016\n\006parent\030\006 \001(\t\022" +
      "\017\n\007address\030\007 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_forge_abi_CreateAssetTx_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_forge_abi_CreateAssetTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forge_abi_CreateAssetTx_descriptor,
        new java.lang.String[] { "Moniker", "Data", "Readonly", "Transferrable", "Ttl", "Parent", "Address", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
