// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delegate.proto

package forge_abi;

public final class Delegate {
  private Delegate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DelegateTxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:forge_abi.DelegateTx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * address of the delegation between sender and receiver
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    java.lang.String getAddress();
    /**
     * <pre>
     * address of the delegation between sender and receiver
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * delegatee's address
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    java.lang.String getTo();
    /**
     * <pre>
     * delegatee's address
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     * a list of operations permitted
     * </pre>
     *
     * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
     */
    java.util.List<forge_abi.Delegate.DelegateOp> 
        getOpsList();
    /**
     * <pre>
     * a list of operations permitted
     * </pre>
     *
     * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
     */
    forge_abi.Delegate.DelegateOp getOps(int index);
    /**
     * <pre>
     * a list of operations permitted
     * </pre>
     *
     * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
     */
    int getOpsCount();
    /**
     * <pre>
     * a list of operations permitted
     * </pre>
     *
     * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
     */
    java.util.List<? extends forge_abi.Delegate.DelegateOpOrBuilder> 
        getOpsOrBuilderList();
    /**
     * <pre>
     * a list of operations permitted
     * </pre>
     *
     * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
     */
    forge_abi.Delegate.DelegateOpOrBuilder getOpsOrBuilder(
        int index);

    /**
     * <code>.google.protobuf.Any data = 15;</code>
     */
    boolean hasData();
    /**
     * <code>.google.protobuf.Any data = 15;</code>
     */
    com.google.protobuf.Any getData();
    /**
     * <code>.google.protobuf.Any data = 15;</code>
     */
    com.google.protobuf.AnyOrBuilder getDataOrBuilder();
  }
  /**
   * Protobuf type {@code forge_abi.DelegateTx}
   */
  public  static final class DelegateTx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:forge_abi.DelegateTx)
      DelegateTxOrBuilder {
    // Use DelegateTx.newBuilder() to construct.
    private DelegateTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DelegateTx() {
      address_ = "";
      to_ = "";
      ops_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DelegateTx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                ops_ = new java.util.ArrayList<forge_abi.Delegate.DelegateOp>();
                mutable_bitField0_ |= 0x00000004;
              }
              ops_.add(
                  input.readMessage(forge_abi.Delegate.DelegateOp.parser(), extensionRegistry));
              break;
            }
            case 122: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          ops_ = java.util.Collections.unmodifiableList(ops_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forge_abi.Delegate.internal_static_forge_abi_DelegateTx_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forge_abi.Delegate.internal_static_forge_abi_DelegateTx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              forge_abi.Delegate.DelegateTx.class, forge_abi.Delegate.DelegateTx.Builder.class);
    }

    private int bitField0_;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <pre>
     * address of the delegation between sender and receiver
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * address of the delegation between sender and receiver
     * </pre>
     *
     * <code>string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 2;
    private volatile java.lang.Object to_;
    /**
     * <pre>
     * delegatee's address
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * delegatee's address
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPS_FIELD_NUMBER = 3;
    private java.util.List<forge_abi.Delegate.DelegateOp> ops_;
    /**
     * <pre>
     * a list of operations permitted
     * </pre>
     *
     * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
     */
    public java.util.List<forge_abi.Delegate.DelegateOp> getOpsList() {
      return ops_;
    }
    /**
     * <pre>
     * a list of operations permitted
     * </pre>
     *
     * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
     */
    public java.util.List<? extends forge_abi.Delegate.DelegateOpOrBuilder> 
        getOpsOrBuilderList() {
      return ops_;
    }
    /**
     * <pre>
     * a list of operations permitted
     * </pre>
     *
     * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
     */
    public int getOpsCount() {
      return ops_.size();
    }
    /**
     * <pre>
     * a list of operations permitted
     * </pre>
     *
     * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
     */
    public forge_abi.Delegate.DelegateOp getOps(int index) {
      return ops_.get(index);
    }
    /**
     * <pre>
     * a list of operations permitted
     * </pre>
     *
     * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
     */
    public forge_abi.Delegate.DelegateOpOrBuilder getOpsOrBuilder(
        int index) {
      return ops_.get(index);
    }

    public static final int DATA_FIELD_NUMBER = 15;
    private com.google.protobuf.Any data_;
    /**
     * <code>.google.protobuf.Any data = 15;</code>
     */
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <code>.google.protobuf.Any data = 15;</code>
     */
    public com.google.protobuf.Any getData() {
      return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
    }
    /**
     * <code>.google.protobuf.Any data = 15;</code>
     */
    public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
      return getData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, to_);
      }
      for (int i = 0; i < ops_.size(); i++) {
        output.writeMessage(3, ops_.get(i));
      }
      if (data_ != null) {
        output.writeMessage(15, getData());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, to_);
      }
      for (int i = 0; i < ops_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, ops_.get(i));
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getData());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof forge_abi.Delegate.DelegateTx)) {
        return super.equals(obj);
      }
      forge_abi.Delegate.DelegateTx other = (forge_abi.Delegate.DelegateTx) obj;

      boolean result = true;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getTo()
          .equals(other.getTo());
      result = result && getOpsList()
          .equals(other.getOpsList());
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      if (getOpsCount() > 0) {
        hash = (37 * hash) + OPS_FIELD_NUMBER;
        hash = (53 * hash) + getOpsList().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static forge_abi.Delegate.DelegateTx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.Delegate.DelegateTx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.Delegate.DelegateTx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.Delegate.DelegateTx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.Delegate.DelegateTx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.Delegate.DelegateTx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.Delegate.DelegateTx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static forge_abi.Delegate.DelegateTx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.Delegate.DelegateTx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.Delegate.DelegateTx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(forge_abi.Delegate.DelegateTx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code forge_abi.DelegateTx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:forge_abi.DelegateTx)
        forge_abi.Delegate.DelegateTxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return forge_abi.Delegate.internal_static_forge_abi_DelegateTx_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return forge_abi.Delegate.internal_static_forge_abi_DelegateTx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                forge_abi.Delegate.DelegateTx.class, forge_abi.Delegate.DelegateTx.Builder.class);
      }

      // Construct using forge_abi.Delegate.DelegateTx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOpsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        address_ = "";

        to_ = "";

        if (opsBuilder_ == null) {
          ops_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          opsBuilder_.clear();
        }
        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return forge_abi.Delegate.internal_static_forge_abi_DelegateTx_descriptor;
      }

      public forge_abi.Delegate.DelegateTx getDefaultInstanceForType() {
        return forge_abi.Delegate.DelegateTx.getDefaultInstance();
      }

      public forge_abi.Delegate.DelegateTx build() {
        forge_abi.Delegate.DelegateTx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public forge_abi.Delegate.DelegateTx buildPartial() {
        forge_abi.Delegate.DelegateTx result = new forge_abi.Delegate.DelegateTx(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.address_ = address_;
        result.to_ = to_;
        if (opsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            ops_ = java.util.Collections.unmodifiableList(ops_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.ops_ = ops_;
        } else {
          result.ops_ = opsBuilder_.build();
        }
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof forge_abi.Delegate.DelegateTx) {
          return mergeFrom((forge_abi.Delegate.DelegateTx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(forge_abi.Delegate.DelegateTx other) {
        if (other == forge_abi.Delegate.DelegateTx.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (opsBuilder_ == null) {
          if (!other.ops_.isEmpty()) {
            if (ops_.isEmpty()) {
              ops_ = other.ops_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureOpsIsMutable();
              ops_.addAll(other.ops_);
            }
            onChanged();
          }
        } else {
          if (!other.ops_.isEmpty()) {
            if (opsBuilder_.isEmpty()) {
              opsBuilder_.dispose();
              opsBuilder_ = null;
              ops_ = other.ops_;
              bitField0_ = (bitField0_ & ~0x00000004);
              opsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOpsFieldBuilder() : null;
            } else {
              opsBuilder_.addAllMessages(other.ops_);
            }
          }
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        forge_abi.Delegate.DelegateTx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (forge_abi.Delegate.DelegateTx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object address_ = "";
      /**
       * <pre>
       * address of the delegation between sender and receiver
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * address of the delegation between sender and receiver
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * address of the delegation between sender and receiver
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * address of the delegation between sender and receiver
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * address of the delegation between sender and receiver
       * </pre>
       *
       * <code>string address = 1;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <pre>
       * delegatee's address
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * delegatee's address
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * delegatee's address
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * delegatee's address
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * delegatee's address
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private java.util.List<forge_abi.Delegate.DelegateOp> ops_ =
        java.util.Collections.emptyList();
      private void ensureOpsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          ops_ = new java.util.ArrayList<forge_abi.Delegate.DelegateOp>(ops_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          forge_abi.Delegate.DelegateOp, forge_abi.Delegate.DelegateOp.Builder, forge_abi.Delegate.DelegateOpOrBuilder> opsBuilder_;

      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public java.util.List<forge_abi.Delegate.DelegateOp> getOpsList() {
        if (opsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ops_);
        } else {
          return opsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public int getOpsCount() {
        if (opsBuilder_ == null) {
          return ops_.size();
        } else {
          return opsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public forge_abi.Delegate.DelegateOp getOps(int index) {
        if (opsBuilder_ == null) {
          return ops_.get(index);
        } else {
          return opsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public Builder setOps(
          int index, forge_abi.Delegate.DelegateOp value) {
        if (opsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOpsIsMutable();
          ops_.set(index, value);
          onChanged();
        } else {
          opsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public Builder setOps(
          int index, forge_abi.Delegate.DelegateOp.Builder builderForValue) {
        if (opsBuilder_ == null) {
          ensureOpsIsMutable();
          ops_.set(index, builderForValue.build());
          onChanged();
        } else {
          opsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public Builder addOps(forge_abi.Delegate.DelegateOp value) {
        if (opsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOpsIsMutable();
          ops_.add(value);
          onChanged();
        } else {
          opsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public Builder addOps(
          int index, forge_abi.Delegate.DelegateOp value) {
        if (opsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOpsIsMutable();
          ops_.add(index, value);
          onChanged();
        } else {
          opsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public Builder addOps(
          forge_abi.Delegate.DelegateOp.Builder builderForValue) {
        if (opsBuilder_ == null) {
          ensureOpsIsMutable();
          ops_.add(builderForValue.build());
          onChanged();
        } else {
          opsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public Builder addOps(
          int index, forge_abi.Delegate.DelegateOp.Builder builderForValue) {
        if (opsBuilder_ == null) {
          ensureOpsIsMutable();
          ops_.add(index, builderForValue.build());
          onChanged();
        } else {
          opsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public Builder addAllOps(
          java.lang.Iterable<? extends forge_abi.Delegate.DelegateOp> values) {
        if (opsBuilder_ == null) {
          ensureOpsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ops_);
          onChanged();
        } else {
          opsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public Builder clearOps() {
        if (opsBuilder_ == null) {
          ops_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          opsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public Builder removeOps(int index) {
        if (opsBuilder_ == null) {
          ensureOpsIsMutable();
          ops_.remove(index);
          onChanged();
        } else {
          opsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public forge_abi.Delegate.DelegateOp.Builder getOpsBuilder(
          int index) {
        return getOpsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public forge_abi.Delegate.DelegateOpOrBuilder getOpsOrBuilder(
          int index) {
        if (opsBuilder_ == null) {
          return ops_.get(index);  } else {
          return opsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public java.util.List<? extends forge_abi.Delegate.DelegateOpOrBuilder> 
           getOpsOrBuilderList() {
        if (opsBuilder_ != null) {
          return opsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ops_);
        }
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public forge_abi.Delegate.DelegateOp.Builder addOpsBuilder() {
        return getOpsFieldBuilder().addBuilder(
            forge_abi.Delegate.DelegateOp.getDefaultInstance());
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public forge_abi.Delegate.DelegateOp.Builder addOpsBuilder(
          int index) {
        return getOpsFieldBuilder().addBuilder(
            index, forge_abi.Delegate.DelegateOp.getDefaultInstance());
      }
      /**
       * <pre>
       * a list of operations permitted
       * </pre>
       *
       * <code>repeated .forge_abi.DelegateOp ops = 3;</code>
       */
      public java.util.List<forge_abi.Delegate.DelegateOp.Builder> 
           getOpsBuilderList() {
        return getOpsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          forge_abi.Delegate.DelegateOp, forge_abi.Delegate.DelegateOp.Builder, forge_abi.Delegate.DelegateOpOrBuilder> 
          getOpsFieldBuilder() {
        if (opsBuilder_ == null) {
          opsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              forge_abi.Delegate.DelegateOp, forge_abi.Delegate.DelegateOp.Builder, forge_abi.Delegate.DelegateOpOrBuilder>(
                  ops_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          ops_ = null;
        }
        return opsBuilder_;
      }

      private com.google.protobuf.Any data_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;
      /**
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public com.google.protobuf.Any getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public Builder setData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public Builder setData(
          com.google.protobuf.Any.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public Builder mergeData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public com.google.protobuf.Any.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any data = 15;</code>
       */
      public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : data_;
        }
      }
      /**
       * <code>.google.protobuf.Any data = 15;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:forge_abi.DelegateTx)
    }

    // @@protoc_insertion_point(class_scope:forge_abi.DelegateTx)
    private static final forge_abi.Delegate.DelegateTx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new forge_abi.Delegate.DelegateTx();
    }

    public static forge_abi.Delegate.DelegateTx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DelegateTx>
        PARSER = new com.google.protobuf.AbstractParser<DelegateTx>() {
      public DelegateTx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DelegateTx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DelegateTx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DelegateTx> getParserForType() {
      return PARSER;
    }

    public forge_abi.Delegate.DelegateTx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DelegateOpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:forge_abi.DelegateOp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type_url = 1;</code>
     */
    java.lang.String getTypeUrl();
    /**
     * <code>string type_url = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeUrlBytes();

    /**
     * <code>repeated string rules = 2;</code>
     */
    java.util.List<java.lang.String>
        getRulesList();
    /**
     * <code>repeated string rules = 2;</code>
     */
    int getRulesCount();
    /**
     * <code>repeated string rules = 2;</code>
     */
    java.lang.String getRules(int index);
    /**
     * <code>repeated string rules = 2;</code>
     */
    com.google.protobuf.ByteString
        getRulesBytes(int index);
  }
  /**
   * <pre>
   * if rules are empty, signature for this type_url is entirely delegated
   * otherwise rules are checked one by one, relationship between rules is AND.
   * a rule is an expression defined in rule_parser
   * (github.com/arcblock/rule-parser) one can setup
   * </pre>
   *
   * Protobuf type {@code forge_abi.DelegateOp}
   */
  public  static final class DelegateOp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:forge_abi.DelegateOp)
      DelegateOpOrBuilder {
    // Use DelegateOp.newBuilder() to construct.
    private DelegateOp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DelegateOp() {
      typeUrl_ = "";
      rules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DelegateOp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              typeUrl_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                rules_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              rules_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          rules_ = rules_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forge_abi.Delegate.internal_static_forge_abi_DelegateOp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forge_abi.Delegate.internal_static_forge_abi_DelegateOp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              forge_abi.Delegate.DelegateOp.class, forge_abi.Delegate.DelegateOp.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_URL_FIELD_NUMBER = 1;
    private volatile java.lang.Object typeUrl_;
    /**
     * <code>string type_url = 1;</code>
     */
    public java.lang.String getTypeUrl() {
      java.lang.Object ref = typeUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string type_url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeUrlBytes() {
      java.lang.Object ref = typeUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RULES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList rules_;
    /**
     * <code>repeated string rules = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRulesList() {
      return rules_;
    }
    /**
     * <code>repeated string rules = 2;</code>
     */
    public int getRulesCount() {
      return rules_.size();
    }
    /**
     * <code>repeated string rules = 2;</code>
     */
    public java.lang.String getRules(int index) {
      return rules_.get(index);
    }
    /**
     * <code>repeated string rules = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRulesBytes(int index) {
      return rules_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, typeUrl_);
      }
      for (int i = 0; i < rules_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rules_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, typeUrl_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < rules_.size(); i++) {
          dataSize += computeStringSizeNoTag(rules_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRulesList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof forge_abi.Delegate.DelegateOp)) {
        return super.equals(obj);
      }
      forge_abi.Delegate.DelegateOp other = (forge_abi.Delegate.DelegateOp) obj;

      boolean result = true;
      result = result && getTypeUrl()
          .equals(other.getTypeUrl());
      result = result && getRulesList()
          .equals(other.getRulesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getTypeUrl().hashCode();
      if (getRulesCount() > 0) {
        hash = (37 * hash) + RULES_FIELD_NUMBER;
        hash = (53 * hash) + getRulesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static forge_abi.Delegate.DelegateOp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.Delegate.DelegateOp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.Delegate.DelegateOp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.Delegate.DelegateOp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.Delegate.DelegateOp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.Delegate.DelegateOp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.Delegate.DelegateOp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static forge_abi.Delegate.DelegateOp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.Delegate.DelegateOp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.Delegate.DelegateOp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(forge_abi.Delegate.DelegateOp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * if rules are empty, signature for this type_url is entirely delegated
     * otherwise rules are checked one by one, relationship between rules is AND.
     * a rule is an expression defined in rule_parser
     * (github.com/arcblock/rule-parser) one can setup
     * </pre>
     *
     * Protobuf type {@code forge_abi.DelegateOp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:forge_abi.DelegateOp)
        forge_abi.Delegate.DelegateOpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return forge_abi.Delegate.internal_static_forge_abi_DelegateOp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return forge_abi.Delegate.internal_static_forge_abi_DelegateOp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                forge_abi.Delegate.DelegateOp.class, forge_abi.Delegate.DelegateOp.Builder.class);
      }

      // Construct using forge_abi.Delegate.DelegateOp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        typeUrl_ = "";

        rules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return forge_abi.Delegate.internal_static_forge_abi_DelegateOp_descriptor;
      }

      public forge_abi.Delegate.DelegateOp getDefaultInstanceForType() {
        return forge_abi.Delegate.DelegateOp.getDefaultInstance();
      }

      public forge_abi.Delegate.DelegateOp build() {
        forge_abi.Delegate.DelegateOp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public forge_abi.Delegate.DelegateOp buildPartial() {
        forge_abi.Delegate.DelegateOp result = new forge_abi.Delegate.DelegateOp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.typeUrl_ = typeUrl_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          rules_ = rules_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.rules_ = rules_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof forge_abi.Delegate.DelegateOp) {
          return mergeFrom((forge_abi.Delegate.DelegateOp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(forge_abi.Delegate.DelegateOp other) {
        if (other == forge_abi.Delegate.DelegateOp.getDefaultInstance()) return this;
        if (!other.getTypeUrl().isEmpty()) {
          typeUrl_ = other.typeUrl_;
          onChanged();
        }
        if (!other.rules_.isEmpty()) {
          if (rules_.isEmpty()) {
            rules_ = other.rules_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRulesIsMutable();
            rules_.addAll(other.rules_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        forge_abi.Delegate.DelegateOp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (forge_abi.Delegate.DelegateOp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object typeUrl_ = "";
      /**
       * <code>string type_url = 1;</code>
       */
      public java.lang.String getTypeUrl() {
        java.lang.Object ref = typeUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          typeUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type_url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeUrlBytes() {
        java.lang.Object ref = typeUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          typeUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type_url = 1;</code>
       */
      public Builder setTypeUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        typeUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type_url = 1;</code>
       */
      public Builder clearTypeUrl() {
        
        typeUrl_ = getDefaultInstance().getTypeUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string type_url = 1;</code>
       */
      public Builder setTypeUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        typeUrl_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList rules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRulesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          rules_ = new com.google.protobuf.LazyStringArrayList(rules_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string rules = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRulesList() {
        return rules_.getUnmodifiableView();
      }
      /**
       * <code>repeated string rules = 2;</code>
       */
      public int getRulesCount() {
        return rules_.size();
      }
      /**
       * <code>repeated string rules = 2;</code>
       */
      public java.lang.String getRules(int index) {
        return rules_.get(index);
      }
      /**
       * <code>repeated string rules = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRulesBytes(int index) {
        return rules_.getByteString(index);
      }
      /**
       * <code>repeated string rules = 2;</code>
       */
      public Builder setRules(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRulesIsMutable();
        rules_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rules = 2;</code>
       */
      public Builder addRules(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRulesIsMutable();
        rules_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rules = 2;</code>
       */
      public Builder addAllRules(
          java.lang.Iterable<java.lang.String> values) {
        ensureRulesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rules_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rules = 2;</code>
       */
      public Builder clearRules() {
        rules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rules = 2;</code>
       */
      public Builder addRulesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRulesIsMutable();
        rules_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:forge_abi.DelegateOp)
    }

    // @@protoc_insertion_point(class_scope:forge_abi.DelegateOp)
    private static final forge_abi.Delegate.DelegateOp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new forge_abi.Delegate.DelegateOp();
    }

    public static forge_abi.Delegate.DelegateOp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DelegateOp>
        PARSER = new com.google.protobuf.AbstractParser<DelegateOp>() {
      public DelegateOp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DelegateOp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DelegateOp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DelegateOp> getParserForType() {
      return PARSER;
    }

    public forge_abi.Delegate.DelegateOp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forge_abi_DelegateTx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forge_abi_DelegateTx_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forge_abi_DelegateOp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forge_abi_DelegateOp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016delegate.proto\022\tforge_abi\032\031google/prot" +
      "obuf/any.proto\"q\n\nDelegateTx\022\017\n\007address\030" +
      "\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\"\n\003ops\030\003 \003(\0132\025.forge_a" +
      "bi.DelegateOp\022\"\n\004data\030\017 \001(\0132\024.google.pro" +
      "tobuf.Any\"-\n\nDelegateOp\022\020\n\010type_url\030\001 \001(" +
      "\t\022\r\n\005rules\030\002 \003(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_forge_abi_DelegateTx_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_forge_abi_DelegateTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forge_abi_DelegateTx_descriptor,
        new java.lang.String[] { "Address", "To", "Ops", "Data", });
    internal_static_forge_abi_DelegateOp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_forge_abi_DelegateOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forge_abi_DelegateOp_descriptor,
        new java.lang.String[] { "TypeUrl", "Rules", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
