// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: revoke_withdraw.proto

package forge_abi;

public final class RevokeWithdraw {
  private RevokeWithdraw() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RevokeWithdrawTxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:forge_abi.RevokeWithdrawTx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the hash of withdraw tx
     * </pre>
     *
     * <code>string withdraw_tx_hash = 1;</code>
     */
    java.lang.String getWithdrawTxHash();
    /**
     * <pre>
     * the hash of withdraw tx
     * </pre>
     *
     * <code>string withdraw_tx_hash = 1;</code>
     */
    com.google.protobuf.ByteString
        getWithdrawTxHashBytes();
  }
  /**
   * Protobuf type {@code forge_abi.RevokeWithdrawTx}
   */
  public  static final class RevokeWithdrawTx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:forge_abi.RevokeWithdrawTx)
      RevokeWithdrawTxOrBuilder {
    // Use RevokeWithdrawTx.newBuilder() to construct.
    private RevokeWithdrawTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RevokeWithdrawTx() {
      withdrawTxHash_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RevokeWithdrawTx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              withdrawTxHash_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forge_abi.RevokeWithdraw.internal_static_forge_abi_RevokeWithdrawTx_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forge_abi.RevokeWithdraw.internal_static_forge_abi_RevokeWithdrawTx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              forge_abi.RevokeWithdraw.RevokeWithdrawTx.class, forge_abi.RevokeWithdraw.RevokeWithdrawTx.Builder.class);
    }

    public static final int WITHDRAW_TX_HASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object withdrawTxHash_;
    /**
     * <pre>
     * the hash of withdraw tx
     * </pre>
     *
     * <code>string withdraw_tx_hash = 1;</code>
     */
    public java.lang.String getWithdrawTxHash() {
      java.lang.Object ref = withdrawTxHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        withdrawTxHash_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the hash of withdraw tx
     * </pre>
     *
     * <code>string withdraw_tx_hash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWithdrawTxHashBytes() {
      java.lang.Object ref = withdrawTxHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        withdrawTxHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWithdrawTxHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, withdrawTxHash_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWithdrawTxHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, withdrawTxHash_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof forge_abi.RevokeWithdraw.RevokeWithdrawTx)) {
        return super.equals(obj);
      }
      forge_abi.RevokeWithdraw.RevokeWithdrawTx other = (forge_abi.RevokeWithdraw.RevokeWithdrawTx) obj;

      boolean result = true;
      result = result && getWithdrawTxHash()
          .equals(other.getWithdrawTxHash());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WITHDRAW_TX_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getWithdrawTxHash().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(forge_abi.RevokeWithdraw.RevokeWithdrawTx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code forge_abi.RevokeWithdrawTx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:forge_abi.RevokeWithdrawTx)
        forge_abi.RevokeWithdraw.RevokeWithdrawTxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return forge_abi.RevokeWithdraw.internal_static_forge_abi_RevokeWithdrawTx_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return forge_abi.RevokeWithdraw.internal_static_forge_abi_RevokeWithdrawTx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                forge_abi.RevokeWithdraw.RevokeWithdrawTx.class, forge_abi.RevokeWithdraw.RevokeWithdrawTx.Builder.class);
      }

      // Construct using forge_abi.RevokeWithdraw.RevokeWithdrawTx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        withdrawTxHash_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return forge_abi.RevokeWithdraw.internal_static_forge_abi_RevokeWithdrawTx_descriptor;
      }

      public forge_abi.RevokeWithdraw.RevokeWithdrawTx getDefaultInstanceForType() {
        return forge_abi.RevokeWithdraw.RevokeWithdrawTx.getDefaultInstance();
      }

      public forge_abi.RevokeWithdraw.RevokeWithdrawTx build() {
        forge_abi.RevokeWithdraw.RevokeWithdrawTx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public forge_abi.RevokeWithdraw.RevokeWithdrawTx buildPartial() {
        forge_abi.RevokeWithdraw.RevokeWithdrawTx result = new forge_abi.RevokeWithdraw.RevokeWithdrawTx(this);
        result.withdrawTxHash_ = withdrawTxHash_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof forge_abi.RevokeWithdraw.RevokeWithdrawTx) {
          return mergeFrom((forge_abi.RevokeWithdraw.RevokeWithdrawTx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(forge_abi.RevokeWithdraw.RevokeWithdrawTx other) {
        if (other == forge_abi.RevokeWithdraw.RevokeWithdrawTx.getDefaultInstance()) return this;
        if (!other.getWithdrawTxHash().isEmpty()) {
          withdrawTxHash_ = other.withdrawTxHash_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        forge_abi.RevokeWithdraw.RevokeWithdrawTx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (forge_abi.RevokeWithdraw.RevokeWithdrawTx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object withdrawTxHash_ = "";
      /**
       * <pre>
       * the hash of withdraw tx
       * </pre>
       *
       * <code>string withdraw_tx_hash = 1;</code>
       */
      public java.lang.String getWithdrawTxHash() {
        java.lang.Object ref = withdrawTxHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          withdrawTxHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the hash of withdraw tx
       * </pre>
       *
       * <code>string withdraw_tx_hash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWithdrawTxHashBytes() {
        java.lang.Object ref = withdrawTxHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          withdrawTxHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the hash of withdraw tx
       * </pre>
       *
       * <code>string withdraw_tx_hash = 1;</code>
       */
      public Builder setWithdrawTxHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        withdrawTxHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the hash of withdraw tx
       * </pre>
       *
       * <code>string withdraw_tx_hash = 1;</code>
       */
      public Builder clearWithdrawTxHash() {
        
        withdrawTxHash_ = getDefaultInstance().getWithdrawTxHash();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the hash of withdraw tx
       * </pre>
       *
       * <code>string withdraw_tx_hash = 1;</code>
       */
      public Builder setWithdrawTxHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        withdrawTxHash_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:forge_abi.RevokeWithdrawTx)
    }

    // @@protoc_insertion_point(class_scope:forge_abi.RevokeWithdrawTx)
    private static final forge_abi.RevokeWithdraw.RevokeWithdrawTx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new forge_abi.RevokeWithdraw.RevokeWithdrawTx();
    }

    public static forge_abi.RevokeWithdraw.RevokeWithdrawTx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RevokeWithdrawTx>
        PARSER = new com.google.protobuf.AbstractParser<RevokeWithdrawTx>() {
      public RevokeWithdrawTx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RevokeWithdrawTx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RevokeWithdrawTx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RevokeWithdrawTx> getParserForType() {
      return PARSER;
    }

    public forge_abi.RevokeWithdraw.RevokeWithdrawTx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_forge_abi_RevokeWithdrawTx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_forge_abi_RevokeWithdrawTx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025revoke_withdraw.proto\022\tforge_abi\",\n\020Re" +
      "vokeWithdrawTx\022\030\n\020withdraw_tx_hash\030\001 \001(\t" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_forge_abi_RevokeWithdrawTx_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_forge_abi_RevokeWithdrawTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_forge_abi_RevokeWithdrawTx_descriptor,
        new java.lang.String[] { "WithdrawTxHash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
